### ISSUE TITLE
LSL push_sample requires timestamps in same time base as LSL local_clock

### ISSUE THREAD

**Issue by cboulay** [WorshipCookies/ApplicationLSL_Test#1]
Hello, I'm one of the LSL maintainers.

First, thank you very much for writing an LSL application.

An LSL user has reached out to me asking for support trying to synchronize their Empatica streams with other LSL streams from other devices (e.g., a keyboard). Unfortunately, with the current usage of LSL in this application, it is impossible to synchronize the Empatica streams with any other LSL stream.

Briefly, in addition to the data stream, behind the scenes LSL maintains another clock_offset stream between the sender and receiver, where the receiving computer calculates the offset between its clock and the sending computer's clock. These clock offsets are stored in the footer of the xdf file. Later, when loading the XDF file with pyxdf or xdf-Matlab, the clock_offsets are used to adjust the timestamps from their stored value into a common time base. In this way, all streams are synchronized upon file loading. The key here is that the clock_offset stream always uses LSL's `local_clock` on each respective computer.

Thus, the data timestamps on the sending computer must also use LSL's local_clock for their values to be adjusted properly upon file load.

In this application, the timestamps are provided manually but they are not using LSL's local_clock. They come direct from the BLEServer, which is definitely not the same as the outlet's LSL local_clock.

https://github.com/WorshipCookies/LabStreamLayer_Applications/blob/7f8d6a4b702d9e4c3c095bede4348320c8147607/LabStreamLayer-AppTest/EmpaticaE4-Recorder/MainWindow.xaml.cs#L367-L374

I have a few possible solutions to propose.

1. Don't send the timestamp at all, let LSL use its default timestamps of time of pushed, and live with the inaccuracy due to the delay between the time the sample was acquired and the time it was pushed.
2. Same as 1, except make all your data streams have more channels, where the extra channels store the timestamp off the device. This way you can synchronize Empatica streams with each other more precisely during offline processing, but it won't help you sync them with non-Empatica streams.
3. When the message is received from the BLEServer, enqueue the message along with the LSL local_clock time of receipt, then re-use that time when pushing the sample.
4. Same as 3, but subtract a constant offset from the time-of-receipt that corresponds to the known delay in sample_acquisition to sample_available_via_BLE.

1 is the easiest, the most common, and probably not much worse technically given how slow wrist band signals are relative to the in-app time from BLE to sending. 2 means you never lose information but can be confusing to users, especially if the timestamps require more precision than the data, so they are spanned across multiple channels. IMO 3 is the best, or 4 if you know what that offset is.

Best regards,
Chad

**Comment by WorshipCookies** [comment]
Hi Chad, 

Thanks for reaching out! I have to admit I haven't touched this code in ages, but if I am not mistaken I ended up using the first solution you stated.

However, I recall when I observed the data streams, I did realize this and ended using LSL's default clock for my own personal research, as the error was not overly substantial (I was actually only interested in the GSR data, not BVP despite collecting it).

Empatica's GSR sensor has a sampling rate of 4Hz (if I remember correctly), so in the end it wasn't too substantial. Given the method that Empatica employs, there is not much around this problem unfortunately, unless they now provide a more accurate sync error between device and server.

Best,
Phil

**Comment by cboulay** [comment]
Hi @WorshipCookies, will you be able to modify the code linked above for all sensors so that it doesn't push timestamps? 

While I've instructed the user to do the same, there might be other users out in the wild or future users who will come across this repo.

**Comment by FelixCarter** [comment]
Hi Phil,

I'm the user in question. Thanks first off for writing the only app I've found that seems to work for linking E4 to LSL! If I can get the LSL timestamps instead of the E4, this would be absolutely perfect for my research (I need to synchronize multiple E4 devices).  

Can you remember how you implemented Chad's first suggestion? I have tried editing the MainWindow.xaml code to prevent it pushing timestamps from the E4 i.e., replaced 
lslXXXOutlet.PushSample(xxxValue, timestamp); 
with lslXXXOutlet.PushSample(xxxValue);

However, upon importing the xdf into Matlab, the time stamps appear to still be from the E4 (i.e. are in UNIX time) although the 'time created' seems to now be from LSL, so Chad's suggestion has definitely worked for the 'time created' field at least. Is there another CS file I need to edit to stop timestamps being sent? I have had a look but can't seem to find anything. 

Many thanks,

Felix

**Comment by WorshipCookies** [comment]
Hi @FelixCarter, 

I appreciate it! From what I understood from @cboulay that is exactly it, simply use the PushSample(Value), without the timestamp. Make sure this is done for all channels (i.e. BVP, GSR and Temp).

As I discussed with @cboulay it has been a long time since I used an Empatica (and I do not have one to test or debug the current code, unfortunately). Let me know if you fix it, and feel free to update the code if you wish :)

Phil

**Comment by FelixCarter** [comment]
Sorry for the noobish question, but after editing the MainWindow.xaml file, do I need to then need to run a compiler for the changes to take effect? I'm trying to understand why removing the 'timestamp' argument from lslGSROutlet.PushSample doesn't seem to work.  

Also, does it matter which version of EmpaticaE4-Recorder I run? There's many different versions (e.g. one each in the Debug and Release folders within both the bin and obj folders)

I appreciate it's difficult to answer questions on something you worked on so long ago - I'd just really love to get this working and I feel like I'm really close - just need to sort out these timestamps!

**Comment by WorshipCookies** [comment]
Hi Felix, 

Yes you should compile your code every time you make a change, or else the effect will not take place (you are running an older version of the .exe). 

In terms of the version of EmpaticaE4, what IDE are you using? If you're in Visual Studio for example you usually can define the type of .exe, the debug folder often includes additional code for the purposes of debugging your source code, while the release does not. In my application both versions should be the same.

**Comment by FelixCarter** [comment]
Oh wow, that makes a lot more sense than what I was doing haha 

I'm very excited to report that it works! In case anybody else comes across this issue in future, as well as removing the 'timestamp' argument from lslxxxOutlet.PushSample in MainWindow.xaml, you need to remove 'timestamp' where PushSample is defined in LSLStreamer.  

Thanks so much @cboulay for your help, and @WorshipCookies for your help and also making such a great and useful app - much appreciated!

**Comment by WorshipCookies** [comment]
Awesome, I will try to update the code over the course of the week with the alterations.

**Comment by WorshipCookies** [comment]
@cboulay The code has been updated to reflect the comments. Everything should be fixed!

**Comment by cboulay** [comment]
That's great. Thanks everyone.
